version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_todo_db:/var/lib/postgresql/data
    container_name: db-postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TodoSogeti
  backend: 
    build: ./back/
    container_name: backend-springboot
    environment:
      - SPRING_PROFILE=prod
      - DB_URL=jdbc:postgresql://db:5432/TodoSogeti
      - DB_USER=admin
      - DB_PASSWORD=admin
    depends_on: 
      - db
  frontend:
    depends_on:
      - backend
    build: ./front/
    container_name: front-angular
    ports:
      - "80:80"
volumes:
  postgres_todo_db: